# Data Types

In [2]:
from datascience import *
import numpy as np

## Tables ##

A table is given a name (such as `nba`) in our programming environment so that we can perform operations on the whole table.

In [3]:
# From https://github.com/erikgregorywebb/datasets/blob/master/nba-salaries.csv
nba = Table.read_table('nba_salaries.csv')
nba

rank,name,position,team,salary,season
1,Shaquille O'Neal,C,Los Angeles Lakers,17142000,2000
2,Kevin Garnett,PF,Minnesota Timberwolves,16806000,2000
3,Alonzo Mourning,C,Miami Heat,15004000,2000
4,Juwan Howard,PF,Washington Wizards,15000000,2000
5,Scottie Pippen,SF,Portland Trail Blazers,14795000,2000
6,Karl Malone,PF,Utah Jazz,14000000,2000
7,Larry Johnson,F,New York Knicks,11910000,2000
8,Gary Payton,PG,Seattle SuperSonics,11020000,2000
9,Rasheed Wallace,PF,Portland Trail Blazers,10800000,2000
10,Shawn Kemp,C,Cleveland Cavaliers,10780000,2000


Manipulating the table creates a new table, but doesn't change/lose the original.

In [15]:
nba.select('name')

name
Shaquille O'Neal
Kevin Garnett
Alonzo Mourning
Juwan Howard
Scottie Pippen
Karl Malone
Larry Johnson
Gary Payton
Rasheed Wallace
Shawn Kemp


In [18]:
nba.drop('rank', 'position').sort('name')

name,team,salary,season
A.C. Green,Miami Heat,2250000,2001
A.J. Guyton,Chicago Bulls,316000,2001
A.J. Guyton,Chicago Bulls,465000,2002
A.J. Price,Indiana Pacers,457588,2010
A.J. Price,Indiana Pacers,762195,2011
A.J. Price,Indiana Pacers,854389,2012
A.J. Price,Washington Wizards,854389,2013
A.J. Price,Phoenix Suns,53838,2015
AJ Hammons,Dallas Mavericks,650000,2017
AJ Hammons,Miami Heat,1312611,2018


In [25]:
nba.sort('name')

rank,name,position,team,salary,season
180,A.C. Green,F,Miami Heat,2250000,2001
355,A.J. Guyton,G,Chicago Bulls,316000,2001
384,A.J. Guyton,G,Chicago Bulls,465000,2002
441,A.J. Price,PG,Indiana Pacers,457588,2010
444,A.J. Price,PG,Indiana Pacers,762195,2011
414,A.J. Price,PG,Indiana Pacers,854389,2012
445,A.J. Price,PG,Washington Wizards,854389,2013
522,A.J. Price,PG,Phoenix Suns,53838,2015
477,AJ Hammons,C,Dallas Mavericks,650000,2017
418,AJ Hammons,C,Miami Heat,1312611,2018


In [ ]:
'nba'

Because each operation creates a new table, multiple operations can be applied.

In [26]:
nba.where('position', 'PG')

rank,name,position,team,salary,season
8,Gary Payton,PG,Seattle SuperSonics,11020000,2000
11,Damon Stoudamire,PG,Portland Trail Blazers,10125000,2000
20,Stephon Marbury,PG,New Jersey Nets,9000000,2000
24,Nick Van Exel,PG,Denver Nuggets,8354000,2000
26,Terrell Brandon,PG,Minnesota Timberwolves,7400000,2000
34,Jason Kidd,PG,Phoenix Suns,6858000,2000
35,Kenny Anderson,PG,Boston Celtics,6680000,2000
39,Steve Nash,PG,Dallas Mavericks,5500000,2000
55,Charlie Ward,PG,New York Knicks,4540000,2000
61,Darrel Armstrong,PG,Orlando Magic,4125000,2000


In [29]:
nba.where('name', "Shaquille O'Neal")

rank,name,position,team,salary,season
1,Shaquille O'Neal,C,Los Angeles Lakers,17142000,2000
2,Shaquille O'Neal,C,Los Angeles Lakers,19285000,2001
2,Shaquille O'Neal,C,Los Angeles Lakers,21428000,2002
2,Shaquille O'Neal,C,Los Angeles Lakers,23571000,2003
2,Shaquille O'Neal,C,Los Angeles Lakers,26571000,2004
1,Shaquille O'Neal,C,Miami Heat,29464000,2005
1,Shaquille O'Neal,C,Miami Heat,20000000,2006
2,Shaquille O'Neal,C,Miami Heat,20000000,2007
2,Shaquille O'Neal,C,Phoenix Suns,21000000,2008
5,Shaquille O'Neal,C,Phoenix Suns,21000000,2009


The result of applying operations is a table, which can also be given a name (e.g., `point_guards`) in our programming environment.

In [30]:
point_guards = nba.where('position', 'PG').drop('rank', 'position')
point_guards

name,team,salary,season
Gary Payton,Seattle SuperSonics,11020000,2000
Damon Stoudamire,Portland Trail Blazers,10125000,2000
Stephon Marbury,New Jersey Nets,9000000,2000
Nick Van Exel,Denver Nuggets,8354000,2000
Terrell Brandon,Minnesota Timberwolves,7400000,2000
Jason Kidd,Phoenix Suns,6858000,2000
Kenny Anderson,Boston Celtics,6680000,2000
Steve Nash,Dallas Mavericks,5500000,2000
Charlie Ward,New York Knicks,4540000,2000
Darrel Armstrong,Orlando Magic,4125000,2000


In [33]:
point_guards.where('season', 2020).sort('name').sort('team')

name,team,salary,season
Brandon Goodwin,Atlanta Hawks,522738,2020
Trae Young,Atlanta Hawks,6273000,2020
Brad Wanamaker,Boston Celtics,1445697,2020
Carsen Edwards,Boston Celtics,1228026,2020
Kemba Walker,Boston Celtics,32742000,2020
Marcus Smart,Boston Celtics,12553571,2020
Kyrie Irving,Brooklyn Nets,31742000,2020
Spencer Dinwiddie,Brooklyn Nets,10605600,2020
Devonte' Graham,Charlotte Hornets,1416852,2020
Terry Rozier,Charlotte Hornets,19894737,2020


In [ ]:
nba

Sorting can be performed in descending order as well.

In [34]:
point_guards.where('season', 2020).sort('salary').show(10)

name,team,salary,season
Ky Bowman,Golden State Warriors,350189,2020
Reggie Jackson,LA Clippers,512721,2020
Brandon Goodwin,Atlanta Hawks,522738,2020
Chris Clemons,Houston Rockets,563347,2020
Justin Robinson,Washington Wizards,898310,2020
Jalen Lecque,Phoenix Suns,898310,2020
Gary Payton II,Washington Wizards,1052909,2020
Carsen Edwards,Boston Celtics,1228026,2020
Devonte' Graham,Charlotte Hornets,1416852,2020
Jevon Carter,Phoenix Suns,1416852,2020


In [35]:
point_guards.where('season', 2020).sort('salary', descending=True).show(10)

name,team,salary,season
Stephen Curry,Golden State Warriors,40231758,2020
Chris Paul,Oklahoma City Thunder,38506482,2020
Russell Westbrook,Houston Rockets,38506482,2020
John Wall,Washington Wizards,38199000,2020
Kyle Lowry,Toronto Raptors,34996296,2020
Kemba Walker,Boston Celtics,32742000,2020
Mike Conley,Utah Jazz,32511624,2020
Kyrie Irving,Brooklyn Nets,31742000,2020
Damian Lillard,Portland Trail Blazers,29802321,2020
Malcolm Brogdon,Indiana Pacers,20000000,2020


## Numbers ##

In [36]:
30

30

In [37]:
10 * 3    # int

30

In [38]:
10 / 3    # float

3.3333333333333335

In [39]:
10 / 2

5.0

In [40]:
10 ** 3

1000

In [41]:
10 ** 0.5

3.1622776601683795

In [43]:
1234567 ** 89

139574185988226216352411677967079384654819840770263154148901015711434587555916221871855053939370772085656915237689603767083349991793713346471091572628494106076146419389211087459209170823939332677859093756734470172351895079430772488109105692648444480028380122417140932569432824316430008740958025053716735421344729410520681559715479472541631321425013768978692403188995380725532383634472359562908542469547971146457062422356845701571795811721146126639734809904577967012608961528997012178537266420111446716001493476975934877110973383995456863730247

In [44]:
10 / 3

3.3333333333333335

In [45]:
75892745.215489247589274985712

75892745.21548925

In [46]:
75892745.215489247589274985712 - 75892745.21548925

0.0

In [49]:
(13 ** 0.5) ** 2

12.999999999999998

In [48]:
3.605551275463989 * 3.605551275463989

12.999999999999998

In [52]:
int(10 / 5)

2

In [54]:
int(10 / 4)

2

In [55]:
float(3)

3.0

In [56]:
6 / 4

1.5

In [57]:
6 / 4000

0.0015

In [58]:
6 / 400000000000000000000000000000000000000000000000000000000

1.5e-56

In [59]:
400000000000000000000000000000000000000000000000000000000 * 1.5e-56 

6.0

In [60]:
1.5e-56 

1.5e-56

In [61]:
x = 5

In [62]:
x

5

In [63]:
x + 1

6

In [64]:
2x

SyntaxError: invalid decimal literal (207285602.py, line 1)

In [65]:
2 * x

10

## Strings ##

In [70]:
'Flavor'

'Flavor'

In [68]:
flavor = 2

In [69]:
flavor

2

In [ ]:
# The line below causes a name error
# Flavor

In [71]:
"Flavor"

'Flavor'

In [72]:
'Don't always use single quotes'

SyntaxError: unterminated string literal (detected at line 1) (2648065634.py, line 1)

In [73]:
"Don't always use single quotes"

"Don't always use single quotes"

In [74]:
'straw' 'berry' # concatenation

'strawberry'

In [75]:
'straw' + 'berry' # concatenation

'strawberry'

In [77]:
'Chris' + 'Paul' # spaces aren't added for you

'ChrisPaul'

In [78]:
'Chris' + ' ' + 'Paul'

'Chris Paul'

In [79]:
x = 'straw'
y = 'berry'
x + y

'strawberry'

In [80]:
x y

SyntaxError: invalid syntax (1567273689.py, line 1)

In [81]:
'ha' * 100

'hahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahahaha'

In [82]:
'lo' * 5.5

TypeError: can't multiply sequence by non-int of type 'float'

In [83]:
'ha' + 10

TypeError: can only concatenate str (not "int") to str

In [84]:
'ha' + str(10)

'ha10'

In [85]:
'ha' + '10'

'ha10'

In [87]:
'3' + 5

TypeError: can only concatenate str (not "int") to str

In [89]:
int('3') + 5

8

In [90]:
int('3.0')

ValueError: invalid literal for int() with base 10: '3.0'

In [91]:
'3.0'

'3.0'

In [92]:
float('3.0')

3.0

In [96]:
int(3.0)

3

In [93]:
int(float('3.0'))

3

In [94]:
3

3

In [97]:
dot_oh = '.0'
float('3' + dot_oh)

3.0

In [101]:
float('3' + dot_oh) * 7

21.0

## Types ##

In [102]:
type(10)

int

In [103]:
a = 10

In [105]:
a

10

In [104]:
type(a)

int

In [106]:
type(4.5)

float

In [107]:
type('abc')

str

In [108]:
type(nba)

datascience.tables.Table

In [109]:
type(Table.read_table('nba_salaries.csv'))

datascience.tables.Table

In [110]:
type(True)

bool

In [112]:
type(abs(-5))

int

In [113]:
type(abs)

builtin_function_or_method

## Arrays ##

In [114]:
first_four = make_array(1, 2, 3, 4)

In [115]:
first_four

array([1, 2, 3, 4])

In [116]:
array([1, 2, 3, 4])

NameError: name 'array' is not defined

In [117]:
from numpy import array

In [118]:
array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [119]:
first_four

array([1, 2, 3, 4])

In [120]:
first_four * 2

array([2, 4, 6, 8])

In [122]:
first_four ** 2

array([ 1,  4,  9, 16])

In [124]:
(first_four + 1) ** 2

array([ 4,  9, 16, 25])

In [123]:
first_four # array is unchanged, just like when we call show/select/drop on Table

array([1, 2, 3, 4])

In [125]:
next_four = make_array(5, 6, 7, 8)

In [126]:
next_four

array([5, 6, 7, 8])

In [127]:
first_four + next_four

array([ 6,  8, 10, 12])

In [128]:
only_three = make_array(5, 6, 7)

In [129]:
# This line will cause an error 
first_four + only_three

ValueError: operands could not be broadcast together with shapes (4,) (3,) 

In [130]:
str_array = make_array('ha', 'he', 'ho')

In [131]:
str_array

array(['ha', 'he', 'ho'],
      dtype='<U2')

In [132]:
str_array * 4

UFuncTypeError: ufunc 'multiply' did not contain a loop with signature matching types (dtype('<U2'), dtype('int64')) -> None

In [133]:
next_four

array([5, 6, 7, 8])

In [134]:
next_four.item(0)

5

In [138]:
next_four.item(4)

IndexError: index 4 is out of bounds for axis 0 with size 4

In [ ]:
sum(next_four)

In [ ]:
np.average(next_four)

In [ ]:
len(next_four)